const countryList = {
  "NONE" : "None",
  "AUD": "AU",
  "BGN": "BG",
  "BRL": "BR",
  "CAD": "CA",
  "CHF": "CH",
  "CNY": "CN",
  "CZK": "CZ",
  "DKK": "DK",
  "EUR": "EU",
  "GBP": "GB",
  "HKD": "HK",
  "HRK": "HR",
  "HUF": "HU",
  "IDR": "ID",
  "ILS": "IL",
  "INR": "IN",
  "ISK": "IS",
  "JPY": "JP",
  "KRW": "KR",
  "MXN": "M",
  "MYR": "MR",
  "NOK": "NO",
  "NZD": "NZ",
  "PHP": "PH",
  "PLN": "PL",
  "RON": "RO",
  "RUB": "RU",
  "SEK": "SE",
  "SGD": "SG",
  "THB": "TH",
  "TRY": "TR",
  "USD": "US ",
  "ZAR": "ZA"
}
const countrynames = {
  "AUD": "Australian Dollar",
  "BGN": "Bulgarian Lev",
  "BRL": "Brazilian Real",
  "CAD": "Canadian Dollar",
  "CHF": "Swiss Franc",
  "CNY": "Chinese Renminbi Yuan",
  "CZK": "Czech Koruna",
  "DKK": "Danish Krone",
  "EUR": "Euro",
  "GBP": "British Pound",
  "HKD": "Hong Kong Dollar",
  "HRK": "Croatian Kuna",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli Shekel",
  "INR": "Indian Rupee",
  "ISK": "Icelandic Krona",
  "JPY": "Japanese Yen",
  "KRW": "South Korean Won",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "NOK": "Norwegian Krone",
  "NZD": "New Zealand Dollar",
  "PHP": "Philippine Peso",
  "PLN": "Polish Zloty",
  "RON": "Romanian Leu",
  "RUB": "Russian Ruble",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "THB": "Thai Baht",
  "TRY": "Turkish Lira",
  "USD": "US Dollar",
  "ZAR": "South African Rand"
}
